cbu updater inst steps
rackerlabs/rackspace-how-to pull request #3941
Opened 2020-11-10 21:28 UTC by brett-johnson

2020-11-10 21:31 UTC, catlook requested changes
put the command in back ticks to format it.

2020-11-10 21:31 UTC, catlook commented on content/cloud-backup/update-or-install-the-cloud-backup-agent-on-linux.md
> +registered, simply run the ./cloudbackup-updater. To both install the updater and install
... the `./cloudbackup-updater`. To both ...

2020-11-10 21:39 UTC, catlook approved these changes
good to go

2020-11-10 21:40 UTC, merged

2021-08-20 10:40 UTC, Mint-6263 reviewed
Ok